name: Daily Music Release

concurrency:
  group: daily-music
  cancel-in-progress: false

on:
  schedule:
    - cron: "0 0 * * *"       # 毎日 09:00 JST
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      SUNO_API_KEY:  ${{ secrets.SUNO_API_KEY }}
      DK_EMAIL:      ${{ secrets.DK_EMAIL }}
      DK_PASSWORD:   ${{ secrets.DK_PASSWORD }}
      TOMATRICK_SLACK_WEBHOOK: ${{ secrets.TOMATRICK_SLACK_WEBHOOK }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install -r requirements.txt
          playwright install chromium

      - name: Generate & Upload 10 Tracks
        run: |
          for i in {1..10}; do
            echo "▶ Generating track #$i"
            if python windsurf/scripts/generate_upload.py; then
              echo "✅ Track #$i succeeded"
            else
              echo "⚠️ Track #$i failed"
            fi
          done

      - name: Debug Slack Webhook   # （必要に応じて確認用に入れてください）
        run: echo ">> webhook='$TOMATRICK_SLACK_WEBHOOK'"

      - name: Slack Success
        if: ${{ always() }}
        run: |
          curl -X POST -H 'Content-Type: application/json' \
            --data '{"text":"✅ tomatrick-music: 10 daily tracks processed."}' \
            "$TOMATRICK_SLACK_WEBHOOK"

      - name: Slack Failure
        if: failure()
        run: |
          curl -X POST -H 'Content-Type: application/json' \
            --data '{"text":"❌ tomatrick-music: Workflow failed. See '"$GITHUB_RUN_URL"'"}' \
            "$TOMATRICK_SLACK_WEBHOOK"
