name: Daily Music Release

concurrency:
  group: daily-music
  cancel-in-progress: false

on:
  schedule:
    # 毎日 09:00 JST → 前日 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch:  # 手動実行も可能

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      SUNO_API_KEY:  ${{ secrets.SUNO_API_KEY }}
      DK_EMAIL:      ${{ secrets.DK_EMAIL }}
      DK_PASSWORD:   ${{ secrets.DK_PASSWORD }}
      # tomatrick-music ワークスペース用 Webhook
      SLACK_WEBHOOK: ${{ secrets.TOMATRICK_SLACK_WEBHOOK }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install chromium

      - name: Generate & Upload 10 Tracks
        run: |
          for i in {1..10}; do
            echo "▶ Generating track #$i"
            if python windsurf/scripts/generate_upload.py; then
              echo "✅ Track #$i succeeded"
            else
              echo "⚠️ Track #$i failed, continuing..."
            fi
          done

      - name: Notify Slack of Success
        if: ${{ always() }}  # 全ループ後に必ず通知
        run: |
          curl -X POST -H 'Content-Type: application/json' \
            --data "{\"text\":\"✅ tomatrick-music: 10 daily tracks processed (some may have failed).\"}" \
            "$SLACK_WEBHOOK"

      - name: Notify Slack of Failure
        if: failure()
        run: |
          curl -X POST -H 'Content-Type: application/json' \
            --data "{\"text\":\"❌ tomatrick-music: Workflow failed. Check logs: $GITHUB_RUN_URL\"}" \
            "$SLACK_WEBHOOK"
