name: Daily Music Release

concurrency:
  group: daily-music
  cancel-in-progress: false

on:
  schedule:
    # 毎日 08:00 JST = 前日 23:00 UTC
    - cron: "0 23 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY:       ${{ secrets.OPENAI_API_KEY }}
      SUNO_API_KEY:         ${{ secrets.SUNO_API_KEY }}
      DK_EMAIL:             ${{ secrets.DK_EMAIL }}
      DK_PASSWORD:          ${{ secrets.DK_PASSWORD }}
      SLACK_WEBHOOK:        ${{ secrets.SLACK_WEBHOOK_TOMATRICK }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install -r requirements.txt
          playwright install chromium

      - name: Generate & Upload 10 Tracks
        run: |
          # 「1日に10曲ずつ」をループで実行
          for i in {1..10}; do
            python windsurf/scripts/generate_upload.py
          done

      - name: Slack Success (tomatrick-music)
        if: success()
        run: |
          curl -X POST -H 'Content-Type: application/json' \
            --data "{\"text\":\"✅ Daily Music Release: 10 tracks uploaded successfully!\"}" \
            "$SLACK_WEBHOOK"

      - name: Slack Failure (tomatrick-music)
        if: failure()
        run: |
          curl -X POST -H 'Content-Type: application/json' \
            --data "{\"text\":\"❌ Daily Music Release failed: $GITHUB_RUN_URL\"}" \
            "$SLACK_WEBHOOK"
